from apps.sales.domain.status import (  # noqa: F401
    PRODUCTION_STATUS_DONE,
    PRODUCTION_STATUS_IN_PROGRESS,
    PRODUCTION_STATUS_PENDING,
    STATUS_CANCELLED,
    STATUS_COMPLETED,
    STATUS_NEW,
    STATUS_PROCESSING,
    STATUS_PRODUCTION,
    STATUS_READY,
    STATUS_SHIPPED,
)
