from django.urls import path

from apps.materials.views import (
    MaterialColorCreateView,
    MaterialColorUpdateView,
    MaterialCreateView,
    MaterialDetailView,
    MaterialListView,
    material_archive,
    material_color_archive,
    material_color_unarchive,
    material_unarchive,
    material_colors_archive,
    materials_archive,
    purchase_add,
    purchase_add_lines,
    purchase_add_from_offer,
    PurchaseOrderDetailView,
    purchase_line_add,
    purchase_line_receive,
    purchase_status_edit,
    purchase_start_material,
    purchase_start_material_offers,
    purchase_request_add,
    PurchaseRequestDetailView,
    purchase_request_line_add,
    purchase_request_line_set_status,
    purchase_request_line_order,
    purchase_request_set_status,
    purchase_requests_list,
    purchase_set_status,
    purchases_list,
    supplier_offer_add,
    SupplierOfferDetailView,
    supplier_offer_start,
    supplier_add,
    SupplierDetailView,
    supplier_offers_list,
    supplier_purchase_create,
    suppliers_list,
    purchase_pick_request_line_for_order,
)

urlpatterns = [
    path("materials/", MaterialListView.as_view(), name="materials"),
    path("materials/add/", MaterialCreateView.as_view(), name="material_add"),
    path("materials/archive/", materials_archive, name="materials_archive"),
    path("materials/<int:pk>/", MaterialDetailView.as_view(), name="material_detail"),
    path("materials/<int:pk>/archive/", material_archive, name="material_archive"),
    path("materials/<int:pk>/unarchive/", material_unarchive, name="material_unarchive"),
    # Material colors
    path(
        "materials/<int:pk>/colors/add/",
        MaterialColorCreateView.as_view(),
        name="material_color_add",
    ),
    path(
        "materials/<int:pk>/colors/<int:color_pk>/",
        MaterialColorUpdateView.as_view(),
        name="material_color_edit",
    ),
    path(
        "materials/<int:pk>/colors/<int:color_pk>/archive/",
        material_color_archive,
        name="material_color_archive",
    ),
    path(
        "materials/<int:pk>/colors/<int:color_pk>/unarchive/",
        material_color_unarchive,
        name="material_color_unarchive",
    ),
    path(
        "materials/<int:pk>/colors/archive/",
        material_colors_archive,
        name="material_colors_archive",
    ),
    # Suppliers
    path("suppliers/", suppliers_list, name="suppliers"),
    path("suppliers/add/", supplier_add, name="supplier_add"),
    path("suppliers/offers/add/", supplier_offer_start, name="supplier_offer_start"),
    path("suppliers/offers/", supplier_offers_list, name="supplier_offers"),
    path("suppliers/offers/<int:pk>/", SupplierOfferDetailView.as_view(), name="supplier_offer_detail"),
    path("suppliers/<int:pk>/", SupplierDetailView.as_view(), name="supplier_detail"),
    path("suppliers/<int:pk>/purchase/create/", supplier_purchase_create, name="supplier_purchase_create"),
    # Purchase orders
    path("purchases/", purchases_list, name="purchases"),
    path("purchases/add/", purchase_add, name="purchase_add"),
    path("purchases/start/", purchase_start_material, name="purchase_start_material"),
    path(
        "purchases/start/materials/<int:material_pk>/",
        purchase_start_material_offers,
        name="purchase_start_material_offers",
    ),
    path(
        "purchases/start/materials/<int:material_pk>/offers/add/",
        supplier_offer_add,
        name="supplier_offer_add",
    ),
    path(
        "purchases/start/offers/<int:offer_pk>/add/",
        purchase_add_from_offer,
        name="purchase_add_from_offer",
    ),
    path("purchases/<int:pk>/add-lines/", purchase_add_lines, name="purchase_add_lines"),
    path("purchases/<int:pk>/", PurchaseOrderDetailView.as_view(), name="purchase_detail"),
    path("purchases/<int:pk>/status/edit/", purchase_status_edit, name="purchase_status_edit"),
    path("purchases/<int:pk>/status/", purchase_set_status, name="purchase_set_status"),
    path("purchases/<int:pk>/lines/add/", purchase_line_add, name="purchase_line_add"),
    path(
        "purchases/<int:pk>/from-request/",
        purchase_pick_request_line_for_order,
        name="purchase_pick_request_line_for_order",
    ),
    path(
        "purchases/<int:pk>/lines/<int:line_pk>/receive/",
        purchase_line_receive,
        name="purchase_line_receive",
    ),
    # Purchase requests
    path("purchase-requests/", purchase_requests_list, name="purchase_requests"),
    path("purchase-requests/add/", purchase_request_add, name="purchase_request_add"),
    path(
        "purchase-requests/<int:pk>/",
        PurchaseRequestDetailView.as_view(),
        name="purchase_request_detail",
    ),
    path(
        "purchase-requests/<int:pk>/status/",
        purchase_request_set_status,
        name="purchase_request_set_status",
    ),
    path(
        "purchase-requests/<int:pk>/lines/add/",
        purchase_request_line_add,
        name="purchase_request_line_add",
    ),
    path(
        "purchase-requests/lines/<int:line_pk>/order/",
        purchase_request_line_order,
        name="purchase_request_line_order",
    ),
    path(
        "purchase-requests/lines/<int:line_pk>/status/",
        purchase_request_line_set_status,
        name="purchase_request_line_set_status",
    ),
]
