# Generated by Django 5.1.6 on 2026-02-09 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('kind', models.CharField(choices=[('production', 'Виробництво'), ('storage', 'Склад'), ('retail', 'Роздріб'), ('transit', 'Транзит')], default='storage', max_length=20)),
                ('is_default_for_production', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('name',),
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_default_for_production', True)), fields=('is_default_for_production',), name='warehouses_one_active_default_for_production')],
            },
        ),
    ]
