# Generated by Django 5.1.6 on 2026-02-09 22:24

from django.db import migrations


def seed_main_warehouse(apps, schema_editor):
    warehouse_model = apps.get_model("warehouses", "Warehouse")
    warehouse_model.objects.update(is_default_for_production=False)
    warehouse_model.objects.get_or_create(
        code="MAIN",
        defaults={
            "name": "Основний склад",
            "kind": "storage",
            "is_default_for_production": True,
            "is_active": True,
        },
    )
    warehouse_model.objects.filter(code="MAIN").update(
        name="Основний склад",
        kind="storage",
        is_default_for_production=True,
        is_active=True,
    )


class Migration(migrations.Migration):

    dependencies = [
        ("warehouses", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_main_warehouse, migrations.RunPython.noop),
    ]
