# Generated by Django 5.1.6 on 2026-02-10 12:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_initial'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionOrder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_embroidery', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True, null=True)),
                ('is_urgent', models.BooleanField(default=False)),
                ('is_etsy', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('new', 'Нове'), ('doing', 'Робимо'), ('is_embroidery', 'Вишиваємо'), ('deciding', 'Рішаємо'), ('on_hold', 'Чогось нема'), ('finished', 'Фініш'), ('almost_finished', 'Майже готове')], db_index=True, default='new', max_length=20)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.product')),
                ('sales_order_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_orders', to='sales.salesorderline')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='production_orders', to='catalog.variant')),
            ],
        ),
        migrations.CreateModel(
            name='DelayedNotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delayed_notification_logs', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delayed_notification_logs', to='production.productionorder')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionOrderStatusHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('new_status', models.CharField(choices=[('new', 'Нове'), ('doing', 'Робимо'), ('is_embroidery', 'Вишиваємо'), ('deciding', 'Рішаємо'), ('on_hold', 'Чогось нема'), ('finished', 'Фініш'), ('almost_finished', 'Майже готове')], max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='production.productionorder')),
            ],
        ),
        migrations.AddIndex(
            model_name='productionorder',
            index=models.Index(fields=['status', '-finished_at'], name='prod_order_completed_idx'),
        ),
        migrations.AddConstraint(
            model_name='delayednotificationlog',
            constraint=models.UniqueConstraint(fields=('user', 'order'), name='orders_delayed_notification_user_order_uniq'),
        ),
        migrations.AddIndex(
            model_name='productionorderstatushistory',
            index=models.Index(fields=['order', 'changed_at'], name='production__order_i_f56172_idx'),
        ),
    ]
