# Generated by Django 5.1.6 on 2026-02-15 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionorder',
            name='materials_consumed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
