# Generated by Django 5.1.6 on 2026-02-10 19:38

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('warehouses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('archived_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('contact_name', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=64)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('archived_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='GoodsReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_goods_receipts', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goods_receipts_legacy', to='warehouses.warehouse')),
            ],
            options={
                'ordering': ('-received_at',),
            },
        ),
        migrations.CreateModel(
            name='MaterialColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.IntegerField()),
                ('archived_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='materials.material')),
            ],
            options={
                'ordering': ('material__name', 'name'),
                'unique_together': {('material', 'code'), ('material', 'name')},
            },
        ),
        migrations.CreateModel(
            name='GoodsReceiptLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('unit', models.CharField(choices=[('pcs', 'шт'), ('m', 'м'), ('m2', 'м²'), ('g', 'г'), ('ml', 'мл')], max_length=8)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='materials.goodsreceipt')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goods_receipt_lines', to='materials.material')),
                ('material_color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='goods_receipt_lines', to='materials.materialcolor')),
            ],
            options={
                'ordering': ('receipt_id', 'id'),
            },
        ),
        migrations.CreateModel(
            name='MaterialStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(choices=[('pcs', 'шт'), ('m', 'м'), ('m2', 'м²'), ('g', 'г'), ('ml', 'мл')], max_length=8)),
                ('quantity', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_records', to='materials.material')),
                ('material_color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_records', to='materials.materialcolor')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='material_stock_records_legacy', to='warehouses.warehouse')),
            ],
            options={
                'ordering': ('material__name',),
            },
        ),
        migrations.CreateModel(
            name='MaterialStockTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Чернетка'), ('in_transit', 'В дорозі'), ('completed', 'Завершено'), ('cancelled', 'Скасовано')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_material_stock_transfers', to=settings.AUTH_USER_MODEL)),
                ('from_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='material_stock_transfers_out', to='warehouses.warehouse')),
                ('to_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='material_stock_transfers_in', to='warehouses.warehouse')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='MaterialStockTransferLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('unit', models.CharField(choices=[('pcs', 'шт'), ('m', 'м'), ('m2', 'м²'), ('g', 'г'), ('ml', 'мл')], max_length=8)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_transfer_lines', to='materials.material')),
                ('material_color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_transfer_lines', to='materials.materialcolor')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='materials.materialstocktransfer')),
            ],
            options={
                'ordering': ('transfer_id', 'id'),
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Чернетка'), ('sent', 'Відправлено'), ('partially_received', 'Частково отримано'), ('received', 'Отримано'), ('cancelled', 'Скасовано')], default='draft', max_length=24)),
                ('expected_at', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_purchase_orders', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='materials.supplier')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='goodsreceipt',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods_receipts', to='materials.purchaseorder'),
        ),
        migrations.CreateModel(
            name='PurchaseOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('received_quantity', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12)),
                ('unit', models.CharField(choices=[('pcs', 'шт'), ('m', 'м'), ('m2', 'м²'), ('g', 'г'), ('ml', 'мл')], max_length=8)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_order_lines', to='materials.material')),
                ('material_color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_order_lines', to='materials.materialcolor')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='materials.purchaseorder')),
            ],
            options={
                'ordering': ('purchase_order_id', 'id'),
            },
        ),
        migrations.CreateModel(
            name='MaterialStockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_change', models.DecimalField(decimal_places=3, max_digits=12)),
                ('reason', models.CharField(choices=[('purchase_in', 'Надходження від постачальника'), ('production_out', 'Списання у виробництво'), ('transfer_in', 'Надходження зі складу'), ('transfer_out', 'Переміщення на склад'), ('adjustment_in', 'Коригування +'), ('adjustment_out', 'Коригування -'), ('return_in', 'Повернення')], max_length=24)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_movements', to=settings.AUTH_USER_MODEL)),
                ('related_receipt_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_movements', to='materials.goodsreceiptline')),
                ('stock_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='materials.materialstock')),
                ('related_transfer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_movements', to='materials.materialstocktransfer')),
                ('related_purchase_order_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_movements', to='materials.purchaseorderline')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='goodsreceiptline',
            name='purchase_order_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipt_lines', to='materials.purchaseorderline'),
        ),
        migrations.AddField(
            model_name='goodsreceipt',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goods_receipts', to='materials.supplier'),
        ),
        migrations.CreateModel(
            name='SupplierMaterialOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('sku', models.CharField(blank=True, max_length=128)),
                ('unit', models.CharField(choices=[('pcs', 'шт'), ('m', 'м'), ('m2', 'м²'), ('g', 'г'), ('ml', 'мл')], max_length=8)),
                ('price_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(choices=[('UAH', 'UAH'), ('USD', 'USD'), ('EUR', 'EUR')], default='UAH', max_length=3)),
                ('min_order_quantity', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12)),
                ('lead_time_days', models.PositiveIntegerField(blank=True, null=True)),
                ('url', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('archived_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='materials.material')),
                ('material_color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_offers', to='materials.materialcolor')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='materials.supplier')),
            ],
            options={
                'ordering': ('supplier__name', 'material__name', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='BOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_per_unit', models.DecimalField(decimal_places=3, max_digits=12)),
                ('unit', models.CharField(choices=[('pcs', 'шт'), ('m', 'м'), ('m2', 'м²'), ('g', 'г'), ('ml', 'мл')], max_length=8)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_norms', to='catalog.product')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_norms', to='materials.material')),
            ],
            options={
                'ordering': ('product_id', 'material__name'),
                'unique_together': {('product', 'material')},
            },
        ),
        migrations.AddConstraint(
            model_name='materialstock',
            constraint=models.UniqueConstraint(condition=models.Q(('material_color__isnull', True), ('warehouse__isnull', True)), fields=('material', 'unit'), name='materials_stock_material_unit_null_color_uniq'),
        ),
        migrations.AddConstraint(
            model_name='materialstock',
            constraint=models.UniqueConstraint(condition=models.Q(('material_color__isnull', False), ('warehouse__isnull', True)), fields=('material', 'material_color', 'unit'), name='materials_stock_material_color_unit_uniq'),
        ),
        migrations.AddConstraint(
            model_name='materialstock',
            constraint=models.UniqueConstraint(condition=models.Q(('material_color__isnull', True), ('warehouse__isnull', False)), fields=('warehouse', 'material', 'unit'), name='materials_stock_warehouse_material_unit_null_color_uniq'),
        ),
        migrations.AddConstraint(
            model_name='materialstock',
            constraint=models.UniqueConstraint(condition=models.Q(('material_color__isnull', False), ('warehouse__isnull', False)), fields=('warehouse', 'material', 'material_color', 'unit'), name='materials_stock_warehouse_material_color_unit_uniq'),
        ),
        migrations.AddConstraint(
            model_name='materialstocktransfer',
            constraint=models.CheckConstraint(condition=models.Q(('from_warehouse', models.F('to_warehouse')), _negated=True), name='materials_materialstocktransfer_from_to_different'),
        ),
    ]
