# Generated by Django 5.1.6 on 2026-02-13 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BOM',
        ),
    ]
