# Generated by Django 5.1.6 on 2026-02-10 00:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_initial'),
        ('materials', '0001_initial'),
        ('warehouses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreceipt',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_goods_receipts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='goodsreceipt',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='goods_receipts_legacy', to='warehouses.warehouse'),
        ),
        migrations.AddField(
            model_name='goodsreceiptline',
            name='receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='materials.goodsreceipt'),
        ),
        migrations.AddField(
            model_name='goodsreceiptline',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goods_receipt_lines', to='materials.material'),
        ),
        migrations.AddField(
            model_name='materialcolor',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='materials.material'),
        ),
        migrations.AddField(
            model_name='goodsreceiptline',
            name='material_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='goods_receipt_lines', to='materials.materialcolor'),
        ),
        migrations.AddField(
            model_name='materialmovement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_movements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='materialmovement',
            name='related_receipt_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_movements', to='materials.goodsreceiptline'),
        ),
        migrations.AddField(
            model_name='materialstockrecord',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_records', to='materials.material'),
        ),
        migrations.AddField(
            model_name='materialstockrecord',
            name='material_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_records', to='materials.materialcolor'),
        ),
        migrations.AddField(
            model_name='materialstockrecord',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='material_stock_records_legacy', to='warehouses.warehouse'),
        ),
        migrations.AddField(
            model_name='materialmovement',
            name='stock_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='materials.materialstockrecord'),
        ),
        migrations.AddField(
            model_name='materialstocktransfer',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_material_stock_transfers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='materialstocktransfer',
            name='from_warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='material_stock_transfers_out', to='warehouses.warehouse'),
        ),
        migrations.AddField(
            model_name='materialstocktransfer',
            name='to_warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='material_stock_transfers_in', to='warehouses.warehouse'),
        ),
        migrations.AddField(
            model_name='materialstocktransferline',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_transfer_lines', to='materials.material'),
        ),
        migrations.AddField(
            model_name='materialstocktransferline',
            name='material_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_transfer_lines', to='materials.materialcolor'),
        ),
        migrations.AddField(
            model_name='materialstocktransferline',
            name='transfer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='materials.materialstocktransfer'),
        ),
        migrations.AddField(
            model_name='productmaterial',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_norms', to='materials.material'),
        ),
        migrations.AddField(
            model_name='productmaterial',
            name='product_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_norms', to='catalog.productmodel'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_purchase_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='goodsreceipt',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods_receipts', to='materials.purchaseorder'),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_order_lines', to='materials.material'),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='material_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_order_lines', to='materials.materialcolor'),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='materials.purchaseorder'),
        ),
        migrations.AddField(
            model_name='materialmovement',
            name='related_purchase_order_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_movements', to='materials.purchaseorderline'),
        ),
        migrations.AddField(
            model_name='goodsreceiptline',
            name='purchase_order_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipt_lines', to='materials.purchaseorderline'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='materials.supplier'),
        ),
        migrations.AddField(
            model_name='goodsreceipt',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goods_receipts', to='materials.supplier'),
        ),
        migrations.AddField(
            model_name='suppliermaterialoffer',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='materials.material'),
        ),
        migrations.AddField(
            model_name='suppliermaterialoffer',
            name='material_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_offers', to='materials.materialcolor'),
        ),
        migrations.AddField(
            model_name='suppliermaterialoffer',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='materials.supplier'),
        ),
        migrations.AlterUniqueTogether(
            name='materialcolor',
            unique_together={('material', 'code'), ('material', 'name')},
        ),
        migrations.AddConstraint(
            model_name='materialstockrecord',
            constraint=models.UniqueConstraint(condition=models.Q(('material_color__isnull', True), ('warehouse__isnull', True)), fields=('material', 'unit'), name='materials_stock_material_unit_null_color_uniq'),
        ),
        migrations.AddConstraint(
            model_name='materialstockrecord',
            constraint=models.UniqueConstraint(condition=models.Q(('material_color__isnull', False), ('warehouse__isnull', True)), fields=('material', 'material_color', 'unit'), name='materials_stock_material_color_unit_uniq'),
        ),
        migrations.AddConstraint(
            model_name='materialstockrecord',
            constraint=models.UniqueConstraint(condition=models.Q(('material_color__isnull', True), ('warehouse__isnull', False)), fields=('warehouse', 'material', 'unit'), name='materials_stock_warehouse_material_unit_null_color_uniq'),
        ),
        migrations.AddConstraint(
            model_name='materialstockrecord',
            constraint=models.UniqueConstraint(condition=models.Q(('material_color__isnull', False), ('warehouse__isnull', False)), fields=('warehouse', 'material', 'material_color', 'unit'), name='materials_stock_warehouse_material_color_unit_uniq'),
        ),
        migrations.AddConstraint(
            model_name='materialstocktransfer',
            constraint=models.CheckConstraint(condition=models.Q(('from_warehouse', models.F('to_warehouse')), _negated=True), name='materials_materialstocktransfer_from_to_different'),
        ),
        migrations.AlterUniqueTogether(
            name='productmaterial',
            unique_together={('product_model', 'material')},
        ),
    ]
