# Generated by Django 5.1.6 on 2026-02-14 13:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_delete_bom'),
        ('warehouses', '0002_seed_main_warehouse'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='external_ref',
            field=models.CharField(blank=True, help_text="Номер/посилання замовлення в магазині (необов'язково).", max_length=255),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='tracking_number',
            field=models.CharField(blank=True, help_text="ТТН / трек-номер (необов'язково).", max_length=255),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Чернетка'), ('sent', 'Відправлено'), ('paid', 'Оплачено'), ('in_transit', 'В дорозі'), ('partially_received', 'Частково отримано'), ('received', 'Отримано'), ('cancelled', 'Скасовано')], default='draft', max_length=24),
        ),
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Відкрито'), ('in_progress', 'В роботі'), ('done', 'Закрито'), ('cancelled', 'Скасовано')], default='open', max_length=24)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_purchase_requests', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_requests', to='warehouses.warehouse')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PurchaseRequestLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Відкрито'), ('ordered', 'Замовлено'), ('done', 'Закрито'), ('cancelled', 'Скасовано')], default='open', max_length=24)),
                ('requested_quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('unit', models.CharField(blank=True, choices=[('pcs', 'шт'), ('m', 'м'), ('m2', 'м²'), ('g', 'г'), ('ml', 'мл')], max_length=8, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_request_lines', to='materials.material')),
                ('material_color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_request_lines', to='materials.materialcolor')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='materials.purchaserequest')),
            ],
            options={
                'ordering': ('request_id', 'id'),
            },
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='request_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_order_lines', to='materials.purchaserequestline'),
        ),
        migrations.AddConstraint(
            model_name='purchaserequestline',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('requested_quantity__isnull', True), ('unit__isnull', True)), models.Q(('requested_quantity__isnull', False), ('unit__isnull', False)), _connector='OR'), name='materials_purchaserequestline_norm_quantity_unit_nullability'),
        ),
    ]
