# Generated by Django 5.1.6 on 2026-02-09 20:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_material_created_at_material_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.IntegerField()),
                ('archived_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='materials.material')),
            ],
            options={
                'ordering': ('material__name', 'name'),
                'unique_together': {('material', 'code'), ('material', 'name')},
            },
        ),
    ]
