# Generated by Django 5.1.6 on 2026-02-14 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_purchaseorder_external_ref_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='stock_unit',
            field=models.CharField(blank=True, choices=[('pcs', 'шт'), ('m', 'м'), ('m2', 'м²'), ('g', 'г'), ('ml', 'мл')], help_text='Одиниця обліку на складі (рекомендовано заповнити).', max_length=8, null=True),
        ),
    ]
