# Generated by Django 5.1.6 on 2026-02-09 20:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_productmodel_primary_material_and_more'),
        ('materials', '0003_materialcolor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_per_unit', models.DecimalField(decimal_places=3, max_digits=12)),
                ('unit', models.CharField(choices=[('pcs', 'шт'), ('m', 'м'), ('m2', 'м²'), ('g', 'г'), ('ml', 'мл')], max_length=8)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_norms', to='materials.material')),
                ('product_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_norms', to='catalog.productmodel')),
            ],
            options={
                'ordering': ('product_model_id', 'material__name'),
                'unique_together': {('product_model', 'material')},
            },
        ),
    ]
