# Generated by Django 5.1.6 on 2026-02-09 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0005_supplier_goodsreceipt_goodsreceiptline_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='materialstockrecord',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='materialstockrecord',
            constraint=models.UniqueConstraint(condition=models.Q(('material_color__isnull', True)), fields=('material', 'unit'), name='materials_stock_material_unit_null_color_uniq'),
        ),
        migrations.AddConstraint(
            model_name='materialstockrecord',
            constraint=models.UniqueConstraint(condition=models.Q(('material_color__isnull', False)), fields=('material', 'material_color', 'unit'), name='materials_stock_material_color_unit_uniq'),
        ),
    ]
