# Generated by Django 5.1.6 on 2026-02-14 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0005_material_stock_unit_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialcolor',
            name='code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
