# Generated by Django 5.1.6 on 2026-02-09 22:24

import django.db.models.deletion
from django.db import migrations, models


def backfill_main_warehouse_for_materials(apps, schema_editor):
    warehouse_model = apps.get_model("warehouses", "Warehouse")
    goods_receipt_model = apps.get_model("materials", "GoodsReceipt")
    material_stock_record_model = apps.get_model("materials", "MaterialStockRecord")

    main_warehouse, _ = warehouse_model.objects.get_or_create(
        code="MAIN",
        defaults={
            "name": "Основний склад",
            "kind": "storage",
            "is_default_for_production": True,
            "is_active": True,
        },
    )
    goods_receipt_model.objects.filter(warehouse_id__isnull=True).update(warehouse_id=main_warehouse.id)
    material_stock_record_model.objects.filter(warehouse_id__isnull=True).update(
        warehouse_id=main_warehouse.id
    )


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0006_alter_materialstockrecord_unique_together_and_more'),
        ('warehouses', '0002_seed_main_warehouse'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='materialstockrecord',
            name='materials_stock_material_unit_null_color_uniq',
        ),
        migrations.RemoveConstraint(
            model_name='materialstockrecord',
            name='materials_stock_material_color_unit_uniq',
        ),
        migrations.AddField(
            model_name='goodsreceipt',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='goods_receipts_legacy', to='warehouses.warehouse'),
        ),
        migrations.AddField(
            model_name='materialstockrecord',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='material_stock_records_legacy', to='warehouses.warehouse'),
        ),
        migrations.RunPython(backfill_main_warehouse_for_materials, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='materialstockrecord',
            constraint=models.UniqueConstraint(condition=models.Q(('material_color__isnull', True), ('warehouse__isnull', True)), fields=('material', 'unit'), name='materials_stock_material_unit_null_color_uniq'),
        ),
        migrations.AddConstraint(
            model_name='materialstockrecord',
            constraint=models.UniqueConstraint(condition=models.Q(('material_color__isnull', False), ('warehouse__isnull', True)), fields=('material', 'material_color', 'unit'), name='materials_stock_material_color_unit_uniq'),
        ),
        migrations.AddConstraint(
            model_name='materialstockrecord',
            constraint=models.UniqueConstraint(condition=models.Q(('material_color__isnull', True), ('warehouse__isnull', False)), fields=('warehouse', 'material', 'unit'), name='materials_stock_warehouse_material_unit_null_color_uniq'),
        ),
        migrations.AddConstraint(
            model_name='materialstockrecord',
            constraint=models.UniqueConstraint(condition=models.Q(('material_color__isnull', False), ('warehouse__isnull', False)), fields=('warehouse', 'material', 'material_color', 'unit'), name='materials_stock_warehouse_material_color_unit_uniq'),
        ),
    ]
