# Generated by Django 5.1.6 on 2026-02-09 22:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0007_remove_materialstockrecord_materials_stock_material_unit_null_color_uniq_and_more'),
        ('warehouses', '0002_seed_main_warehouse'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialStockTransfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Чернетка'), ('in_transit', 'В дорозі'), ('completed', 'Завершено'), ('cancelled', 'Скасовано')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_material_stock_transfers', to=settings.AUTH_USER_MODEL)),
                ('from_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='material_stock_transfers_out', to='warehouses.warehouse')),
                ('to_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='material_stock_transfers_in', to='warehouses.warehouse')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='MaterialStockTransferLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('unit', models.CharField(choices=[('pcs', 'шт'), ('m', 'м'), ('m2', 'м²'), ('g', 'г'), ('ml', 'мл')], max_length=8)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_transfer_lines', to='materials.material')),
                ('material_color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_transfer_lines', to='materials.materialcolor')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='materials.materialstocktransfer')),
            ],
            options={
                'ordering': ('transfer_id', 'id'),
            },
        ),
        migrations.AddConstraint(
            model_name='materialstocktransfer',
            constraint=models.CheckConstraint(condition=models.Q(('from_warehouse', models.F('to_warehouse')), _negated=True), name='materials_materialstocktransfer_from_to_different'),
        ),
    ]
