# Generated by Django 5.1.6 on 2026-02-15 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0008_purchase_request_single_line'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialstockmovement',
            name='reason',
            field=models.CharField(choices=[('purchase_in', 'Надходження від постачальника'), ('production_out', 'Списання у виробництво'), ('transfer_in', 'Надходження зі складу'), ('transfer_out', 'Переміщення на склад'), ('adjustment_in', 'Коригування +'), ('adjustment_out', 'Коригування -'), ('write_off', 'Списання'), ('return_in', 'Повернення')], max_length=24),
        ),
    ]
