# Generated by Django 5.1.6 on 2026-02-09 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0008_materialstocktransfer_materialstocktransferline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialmovement',
            name='reason',
            field=models.CharField(choices=[('purchase_in', 'Надходження від постачальника'), ('production_out', 'Списання у виробництво'), ('transfer_in', 'Надходження зі складу'), ('transfer_out', 'Переміщення на склад'), ('adjustment_in', 'Коригування +'), ('adjustment_out', 'Коригування -'), ('return_in', 'Повернення')], max_length=24),
        ),
    ]
