# Generated by Django 5.1.6 on 2026-02-10 12:47

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('instagram', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sales_customer',
            },
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('site', 'Сайт'), ('is_etsy', 'Etsy'), ('wholesale', 'Опт')], max_length=20)),
                ('status', models.CharField(choices=[('new', 'Нове'), ('processing', 'В обробці'), ('production', 'На виробництві'), ('ready', 'Готове до відправки'), ('shipped', 'Відправлено'), ('completed', 'Завершено'), ('cancelled', 'Скасовано')], default='new', max_length=20)),
                ('customer_info', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('payment_status', models.CharField(choices=[('pending', 'Очікує'), ('partial', 'Частково'), ('paid', 'Оплачено')], default='pending', max_length=20)),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Готівка'), ('card', 'Карта'), ('transfer', 'Переказ'), ('other', 'Інше')], max_length=20)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='sales.customer')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='SalesOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('production_mode', models.CharField(choices=[('auto', 'Авто'), ('manual_production', 'Вручну'), ('force_production', 'Тільки виробництво')], default='auto', max_length=24)),
                ('production_status', models.CharField(choices=[('pending', 'Очікує'), ('in_progress', 'У роботі'), ('done', 'Готово')], default='pending', max_length=20)),
                ('bundle_preset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_order_lines', to='catalog.bundlepreset')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.product')),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.salesorder')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_order_lines', to='catalog.variant')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='SalesOrderLineComponentSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.product')),
                ('order_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_selections', to='sales.salesorderline')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_order_line_components', to='catalog.variant')),
            ],
            options={
                'unique_together': {('order_line', 'component')},
            },
        ),
    ]
