# Generated by Django 5.1.6 on 2026-02-15 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesOrderLineBlocker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('missing_materials', 'Немає матеріалів'), ('manual_required', 'Потрібне рішення')], max_length=32)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sales_order_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blockers', to='sales.salesorderline')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['sales_order_line', 'is_active'], name='sales_blocker_line_active_idx')],
            },
        ),
    ]
