# Generated by Django 5.1.6 on 2026-02-10 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_order_created', models.BooleanField(default=True)),
                ('notify_order_finished', models.BooleanField(default=True)),
                ('notify_order_created_pause', models.BooleanField(default=True)),
            ],
        ),
    ]
