# Generated by Django 5.1.6 on 2026-02-09 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0004_productmodel_is_bundle_bundlecolormapping_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('site', 'Сайт'), ('etsy', 'Etsy'), ('wholesale', 'Опт')], max_length=20)),
                ('status', models.CharField(choices=[('new', 'Нове'), ('processing', 'В обробці'), ('production', 'На виробництві'), ('ready', 'Готове до відправки'), ('shipped', 'Відправлено'), ('completed', 'Завершено'), ('cancelled', 'Скасовано')], default='new', max_length=20)),
                ('customer_info', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='CustomerOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('production_mode', models.CharField(choices=[('auto', 'Авто'), ('manual_production', 'Вручну'), ('force_production', 'Тільки виробництво')], default='auto', max_length=24)),
                ('production_status', models.CharField(choices=[('pending', 'Очікує'), ('in_progress', 'У роботі'), ('done', 'Готово')], default='pending', max_length=20)),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.color')),
                ('customer_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='customer_orders.customerorder')),
                ('product_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.productmodel')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='CustomerOrderLineComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.color')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.productmodel')),
                ('order_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_colors', to='customer_orders.customerorderline')),
            ],
            options={
                'unique_together': {('order_line', 'component')},
            },
        ),
    ]
