# Generated by Django 5.1.6 on 2026-02-10 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_initial'),
        ('customer_orders', '0001_initial'),
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorderline',
            name='primary_material_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_order_line_primary_colors', to='materials.materialcolor'),
        ),
        migrations.AddField(
            model_name='customerorderline',
            name='product_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.productmodel'),
        ),
        migrations.AddField(
            model_name='customerorderline',
            name='product_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_order_lines_legacy', to='catalog.productvariant'),
        ),
        migrations.AddField(
            model_name='customerorderline',
            name='secondary_material_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_order_line_secondary_colors', to='materials.materialcolor'),
        ),
        migrations.AddField(
            model_name='customerorderlinecomponent',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.color'),
        ),
        migrations.AddField(
            model_name='customerorderlinecomponent',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.productmodel'),
        ),
        migrations.AddField(
            model_name='customerorderlinecomponent',
            name='order_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_colors', to='customer_orders.customerorderline'),
        ),
        migrations.AddField(
            model_name='customerorderlinecomponent',
            name='primary_material_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_order_component_primary_colors', to='materials.materialcolor'),
        ),
        migrations.AddField(
            model_name='customerorderlinecomponent',
            name='product_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_order_line_components_legacy', to='catalog.productvariant'),
        ),
        migrations.AddField(
            model_name='customerorderlinecomponent',
            name='secondary_material_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_order_component_secondary_colors', to='materials.materialcolor'),
        ),
        migrations.AlterUniqueTogether(
            name='customerorderlinecomponent',
            unique_together={('order_line', 'component')},
        ),
    ]
