# Generated by Django 5.1.6 on 2026-02-09 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_productmodel_primary_material_and_more'),
        ('customer_orders', '0001_initial'),
        ('materials', '0003_materialcolor'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorderline',
            name='bundle_preset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_lines', to='catalog.bundlepreset'),
        ),
        migrations.AddField(
            model_name='customerorderline',
            name='primary_material_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_order_line_primary_colors', to='materials.materialcolor'),
        ),
        migrations.AddField(
            model_name='customerorderline',
            name='secondary_material_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_order_line_secondary_colors', to='materials.materialcolor'),
        ),
        migrations.AddField(
            model_name='customerorderlinecomponent',
            name='primary_material_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_order_component_primary_colors', to='materials.materialcolor'),
        ),
        migrations.AddField(
            model_name='customerorderlinecomponent',
            name='secondary_material_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_order_component_secondary_colors', to='materials.materialcolor'),
        ),
        migrations.AlterField(
            model_name='customerorderlinecomponent',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.color'),
        ),
    ]
