# Generated by Django 5.1.6 on 2026-02-09 22:05

import django.db.models.deletion
from django.db import migrations, models


def _resolve_variant_id(
    *,
    product_variant_model,
    product_id,
    color_id,
    primary_material_color_id,
    secondary_material_color_id,
):
    if color_id is not None:
        if primary_material_color_id is not None or secondary_material_color_id is not None:
            return None
        variant, _ = product_variant_model.objects.get_or_create(
            product_id=product_id,
            color_id=color_id,
            primary_material_color_id=None,
            secondary_material_color_id=None,
            defaults={"is_active": True},
        )
        return variant.id

    if primary_material_color_id is None:
        return None

    variant, _ = product_variant_model.objects.get_or_create(
        product_id=product_id,
        color_id=None,
        primary_material_color_id=primary_material_color_id,
        secondary_material_color_id=secondary_material_color_id,
        defaults={"is_active": True},
    )
    return variant.id


def backfill_customer_order_product_variant(apps, schema_editor):
    line_model = apps.get_model("customer_orders", "CustomerOrderLine")
    component_model = apps.get_model("customer_orders", "CustomerOrderLineComponent")
    product_variant_model = apps.get_model("catalog", "ProductVariant")

    for line in line_model.objects.filter(product_variant_id__isnull=True).iterator():
        variant_id = _resolve_variant_id(
            product_variant_model=product_variant_model,
            product_id=line.product_model_id,
            color_id=line.color_id,
            primary_material_color_id=line.primary_material_color_id,
            secondary_material_color_id=line.secondary_material_color_id,
        )
        if variant_id is None:
            continue
        line_model.objects.filter(id=line.id, product_variant_id__isnull=True).update(
            product_variant_id=variant_id
        )

    for component in component_model.objects.filter(product_variant_id__isnull=True).iterator():
        variant_id = _resolve_variant_id(
            product_variant_model=product_variant_model,
            product_id=component.component_id,
            color_id=component.color_id,
            primary_material_color_id=component.primary_material_color_id,
            secondary_material_color_id=component.secondary_material_color_id,
        )
        if variant_id is None:
            continue
        component_model.objects.filter(id=component.id, product_variant_id__isnull=True).update(
            product_variant_id=variant_id
        )


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_productvariant'),
        ('customer_orders', '0002_customerorderline_bundle_preset_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorderline',
            name='product_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_order_lines_legacy', to='catalog.productvariant'),
        ),
        migrations.AddField(
            model_name='customerorderlinecomponent',
            name='product_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_order_line_components_legacy', to='catalog.productvariant'),
        ),
        migrations.RunPython(backfill_customer_order_product_variant, migrations.RunPython.noop),
    ]
