# Generated by Django 5.1.6 on 2026-02-10 00:34

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('catalog', '0002_initial'),
        ('customer_orders', '0002_initial'),
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('telegram_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Telegram ID')),
                ('theme', models.CharField(choices=[('lumen_subtle', 'Lumen (Subtle)'), ('lumen_warm', 'Lumen (Warm)'), ('lumen_night', 'Lumen (Night)'), ('dune_lite', 'Dune Lite')], default='lumen_subtle', max_length=32, verbose_name='Theme')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('embroidery', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True, null=True)),
                ('urgent', models.BooleanField(default=False)),
                ('etsy', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('current_status', models.CharField(choices=[('new', 'Нове'), ('doing', 'Робимо'), ('embroidery', 'Вишиваємо'), ('deciding', 'Рішаємо'), ('on_hold', 'Чогось нема'), ('finished', 'Фініш'), ('almost_finished', 'Майже готове')], db_index=True, default='new', max_length=20)),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.color')),
                ('customer_order_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_orders', to='customer_orders.customerorderline')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.productmodel')),
                ('primary_material_color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders_primary_colors', to='materials.materialcolor')),
                ('product_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='catalog.productvariant')),
                ('secondary_material_color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders_secondary_colors', to='materials.materialcolor')),
            ],
        ),
        migrations.CreateModel(
            name='DelayedNotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delayed_notification_logs', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delayed_notification_logs', to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('new_status', models.CharField(choices=[('new', 'Нове'), ('doing', 'Робимо'), ('embroidery', 'Вишиваємо'), ('deciding', 'Рішаємо'), ('on_hold', 'Чогось нема'), ('finished', 'Фініш'), ('almost_finished', 'Майже готове')], max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='orders.order')),
            ],
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['current_status', '-finished_at'], name='orders_completed_idx'),
        ),
        migrations.AddConstraint(
            model_name='delayednotificationlog',
            constraint=models.UniqueConstraint(fields=('user', 'order'), name='orders_delayed_notification_user_order_uniq'),
        ),
        migrations.AddIndex(
            model_name='orderstatushistory',
            index=models.Index(fields=['order', 'changed_at'], name='orders_orde_order_i_7978aa_idx'),
        ),
    ]
