# Generated by Django 5.1.6 on 2026-02-09 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_color_created_at_color_updated_at_and_more'),
        ('orders', '0014_customuser_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.color'),
        ),
        migrations.AlterField(
            model_name='order',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.productmodel'),
        ),
    ]
