# Generated by Django 5.1.6 on 2026-02-09 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_orders', '0001_initial'),
        ('orders', '0017_customuser_theme_add_lumen_night'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_order_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_orders', to='customer_orders.customerorderline'),
        ),
    ]
