# Generated by Django 5.1.6 on 2026-02-09 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_productmodel_primary_material_and_more'),
        ('materials', '0003_materialcolor'),
        ('orders', '0018_order_customer_order_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='primary_material_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders_primary_colors', to='materials.materialcolor'),
        ),
        migrations.AddField(
            model_name='order',
            name='secondary_material_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders_secondary_colors', to='materials.materialcolor'),
        ),
        migrations.AlterField(
            model_name='order',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.color'),
        ),
    ]
