# Generated by Django 5.1.6 on 2026-02-09 19:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0004_productmodel_is_bundle_bundlecolormapping_and_more'),
        ('customer_orders', '0001_initial'),
        ('orders', '0018_order_customer_order_line'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.color')),
                ('product_model', models.ForeignKey(limit_choices_to={'is_bundle': False}, on_delete=django.db.models.deletion.PROTECT, to='catalog.productmodel')),
            ],
            options={
                'verbose_name': 'Залишок на складі',
                'verbose_name_plural': 'Залишки на складі',
                'unique_together': {('product_model', 'color')},
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_change', models.IntegerField()),
                ('reason', models.CharField(choices=[('production_in', 'Надходження з виробництва'), ('order_out', 'Відвантаження клієнту'), ('adjustment_in', 'Коригування +'), ('adjustment_out', 'Коригування -'), ('return_in', 'Повернення')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('related_customer_order_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer_orders.customerorderline')),
                ('related_production_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order')),
                ('stock_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.stockrecord')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
