# Generated by Django 5.1.6 on 2026-02-10 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_initial'),
        ('production', '0001_initial'),
        ('sales', '0001_initial'),
        ('warehouses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_stocks', to='catalog.variant')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_stocks', to='warehouses.warehouse')),
            ],
            options={
                'verbose_name': 'Залишок на складі',
                'verbose_name_plural': 'Залишки на складі',
            },
        ),
        migrations.CreateModel(
            name='ProductStockTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Чернетка'), ('in_transit', 'В дорозі'), ('completed', 'Завершено'), ('cancelled', 'Скасовано')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_product_stock_transfers', to=settings.AUTH_USER_MODEL)),
                ('from_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_stock_transfers_out', to='warehouses.warehouse')),
                ('to_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_stock_transfers_in', to='warehouses.warehouse')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ProductStockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_change', models.IntegerField()),
                ('reason', models.CharField(choices=[('production_in', 'Надходження з виробництва'), ('order_out', 'Відвантаження клієнту'), ('transfer_in', 'Надходження зі складу'), ('transfer_out', 'Переміщення на склад'), ('adjustment_in', 'Коригування +'), ('adjustment_out', 'Коригування -'), ('return_in', 'Повернення')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('related_production_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.productionorder')),
                ('sales_order_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.salesorderline')),
                ('stock_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.productstock')),
                ('related_transfer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='inventory.productstocktransfer')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ProductStockTransferLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.productstocktransfer')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_stock_transfer_lines', to='catalog.variant')),
            ],
        ),
        migrations.CreateModel(
            name='WIPStockRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wip_stocks', to='catalog.variant')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wip_stocks', to='warehouses.warehouse')),
            ],
            options={
                'verbose_name': 'WIP залишок',
                'verbose_name_plural': 'WIP залишки',
            },
        ),
        migrations.CreateModel(
            name='WIPStockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_change', models.IntegerField()),
                ('reason', models.CharField(choices=[('cutting_in', 'Порізка в WIP'), ('finishing_out', 'Вибуття з WIP на доробку'), ('scrap_out', 'Списання браку з WIP'), ('adjustment_in', 'Коригування +'), ('adjustment_out', 'Коригування -')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('related_production_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.productionorder')),
                ('stock_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.wipstockrecord')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='productstock',
            constraint=models.UniqueConstraint(fields=('warehouse', 'variant'), name='inventory_stockrecord_warehouse_variant_uniq'),
        ),
        migrations.AddConstraint(
            model_name='productstocktransfer',
            constraint=models.CheckConstraint(condition=models.Q(('from_warehouse', models.F('to_warehouse')), _negated=True), name='inventory_finishedstocktransfer_from_to_different'),
        ),
        migrations.AddConstraint(
            model_name='productstocktransferline',
            constraint=models.UniqueConstraint(fields=('transfer', 'variant'), name='inventory_finishedstocktransferline_transfer_variant_uniq'),
        ),
        migrations.AddConstraint(
            model_name='wipstockrecord',
            constraint=models.UniqueConstraint(fields=('warehouse', 'variant'), name='inventory_wipstockrecord_warehouse_variant_uniq'),
        ),
    ]
