# Generated by Django 5.1.6 on 2026-02-10 00:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_initial'),
        ('customer_orders', '0002_initial'),
        ('inventory', '0001_initial'),
        ('materials', '0001_initial'),
        ('orders', '0001_initial'),
        ('warehouses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='finishedstocktransfer',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_finished_stock_transfers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='finishedstocktransfer',
            name='from_warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finished_stock_transfers_out', to='warehouses.warehouse'),
        ),
        migrations.AddField(
            model_name='finishedstocktransfer',
            name='to_warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finished_stock_transfers_in', to='warehouses.warehouse'),
        ),
        migrations.AddField(
            model_name='finishedstocktransferline',
            name='product_variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finished_stock_transfer_lines', to='catalog.productvariant'),
        ),
        migrations.AddField(
            model_name='finishedstocktransferline',
            name='transfer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.finishedstocktransfer'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='related_customer_order_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer_orders.customerorderline'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='related_production_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order'),
        ),
        migrations.AddField(
            model_name='stockrecord',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.color'),
        ),
        migrations.AddField(
            model_name='stockrecord',
            name='primary_material_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_records_primary_colors', to='materials.materialcolor'),
        ),
        migrations.AddField(
            model_name='stockrecord',
            name='product_model',
            field=models.ForeignKey(limit_choices_to={'is_bundle': False}, on_delete=django.db.models.deletion.PROTECT, to='catalog.productmodel'),
        ),
        migrations.AddField(
            model_name='stockrecord',
            name='product_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_records_legacy', to='catalog.productvariant'),
        ),
        migrations.AddField(
            model_name='stockrecord',
            name='secondary_material_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_records_secondary_colors', to='materials.materialcolor'),
        ),
        migrations.AddField(
            model_name='stockrecord',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finished_stock_records_legacy', to='warehouses.warehouse'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='stock_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.stockrecord'),
        ),
        migrations.AddField(
            model_name='wipstockmovement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wipstockmovement',
            name='related_production_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order'),
        ),
        migrations.AddField(
            model_name='wipstockrecord',
            name='product_variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wip_stock_records', to='catalog.productvariant'),
        ),
        migrations.AddField(
            model_name='wipstockrecord',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wip_stock_records', to='warehouses.warehouse'),
        ),
        migrations.AddField(
            model_name='wipstockmovement',
            name='stock_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.wipstockrecord'),
        ),
        migrations.AddConstraint(
            model_name='finishedstocktransfer',
            constraint=models.CheckConstraint(condition=models.Q(('from_warehouse', models.F('to_warehouse')), _negated=True), name='inventory_finishedstocktransfer_from_to_different'),
        ),
        migrations.AddConstraint(
            model_name='finishedstocktransferline',
            constraint=models.UniqueConstraint(fields=('transfer', 'product_variant'), name='inventory_finishedstocktransferline_transfer_variant_uniq'),
        ),
        migrations.AddConstraint(
            model_name='stockrecord',
            constraint=models.UniqueConstraint(condition=models.Q(('warehouse__isnull', True)), fields=('product_model', 'color'), name='inventory_stockrecord_product_color_uniq'),
        ),
        migrations.AddConstraint(
            model_name='stockrecord',
            constraint=models.UniqueConstraint(condition=models.Q(('warehouse__isnull', True)), fields=('product_model', 'primary_material_color', 'secondary_material_color'), name='inventory_stockrecord_product_material_color_uniq'),
        ),
        migrations.AddConstraint(
            model_name='stockrecord',
            constraint=models.UniqueConstraint(condition=models.Q(('warehouse__isnull', False)), fields=('warehouse', 'product_model', 'color'), name='inventory_stockrecord_warehouse_product_color_uniq'),
        ),
        migrations.AddConstraint(
            model_name='stockrecord',
            constraint=models.UniqueConstraint(condition=models.Q(('warehouse__isnull', False)), fields=('warehouse', 'product_model', 'primary_material_color', 'secondary_material_color'), name='inventory_stockrecord_warehouse_product_material_color_uniq'),
        ),
        migrations.AddConstraint(
            model_name='wipstockrecord',
            constraint=models.UniqueConstraint(fields=('warehouse', 'product_variant'), name='inventory_wipstockrecord_warehouse_variant_uniq'),
        ),
    ]
