# Generated by Django 5.1.6 on 2026-02-15 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_alter_product_kind'),
        ('inventory', '0001_initial'),
        ('sales', '0001_initial'),
        ('warehouses', '0002_seed_main_warehouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstockmovement',
            name='reason',
            field=models.CharField(choices=[('production_in', 'Надходження з виробництва'), ('order_out', 'Відвантаження клієнту'), ('transfer_in', 'Надходження зі складу'), ('transfer_out', 'Переміщення на склад'), ('adjustment_in', 'Коригування +'), ('adjustment_out', 'Коригування -'), ('write_off', 'Списання'), ('return_in', 'Повернення')], max_length=20),
        ),
        migrations.CreateModel(
            name='ProductStockReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Активна'), ('consumed', 'Використана'), ('released', 'Скасована')], db_index=True, default='active', max_length=20)),
                ('quantity', models.PositiveIntegerField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sales_order_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_reservations', to='sales.salesorderline')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_stock_reservations', to='catalog.variant')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_stock_reservations', to='warehouses.warehouse')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['sales_order_line', 'status'], name='inv_res_line_status_idx'), models.Index(fields=['warehouse', 'variant', 'status'], name='inv_res_key_status_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('warehouse', 'variant', 'sales_order_line'), name='inventory_one_active_reservation_per_line_variant_wh')],
            },
        ),
    ]
