# Generated by Django 5.1.6 on 2026-02-09 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_productmodel_primary_material_and_more'),
        ('inventory', '0001_initial'),
        ('materials', '0003_materialcolor'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stockrecord',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='stockrecord',
            name='primary_material_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_records_primary_colors', to='materials.materialcolor'),
        ),
        migrations.AddField(
            model_name='stockrecord',
            name='secondary_material_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_records_secondary_colors', to='materials.materialcolor'),
        ),
        migrations.AlterField(
            model_name='stockrecord',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.color'),
        ),
        migrations.AddConstraint(
            model_name='stockrecord',
            constraint=models.UniqueConstraint(fields=('product_model', 'color'), name='inventory_stockrecord_product_color_uniq'),
        ),
        migrations.AddConstraint(
            model_name='stockrecord',
            constraint=models.UniqueConstraint(fields=('product_model', 'primary_material_color', 'secondary_material_color'), name='inventory_stockrecord_product_material_color_uniq'),
        ),
    ]
