# Generated by Django 5.1.6 on 2026-02-09 22:05

import django.db.models.deletion
from django.db import migrations, models


def _resolve_variant_id(
    *,
    product_variant_model,
    product_id,
    color_id,
    primary_material_color_id,
    secondary_material_color_id,
):
    if color_id is not None:
        if primary_material_color_id is not None or secondary_material_color_id is not None:
            return None
        variant, _ = product_variant_model.objects.get_or_create(
            product_id=product_id,
            color_id=color_id,
            primary_material_color_id=None,
            secondary_material_color_id=None,
            defaults={"is_active": True},
        )
        return variant.id

    if primary_material_color_id is None:
        return None

    variant, _ = product_variant_model.objects.get_or_create(
        product_id=product_id,
        color_id=None,
        primary_material_color_id=primary_material_color_id,
        secondary_material_color_id=secondary_material_color_id,
        defaults={"is_active": True},
    )
    return variant.id


def backfill_stock_record_product_variant(apps, schema_editor):
    stock_record_model = apps.get_model("inventory", "StockRecord")
    product_variant_model = apps.get_model("catalog", "ProductVariant")

    for stock_record in stock_record_model.objects.filter(product_variant_id__isnull=True).iterator():
        variant_id = _resolve_variant_id(
            product_variant_model=product_variant_model,
            product_id=stock_record.product_model_id,
            color_id=stock_record.color_id,
            primary_material_color_id=stock_record.primary_material_color_id,
            secondary_material_color_id=stock_record.secondary_material_color_id,
        )
        if variant_id is None:
            continue
        stock_record_model.objects.filter(id=stock_record.id, product_variant_id__isnull=True).update(
            product_variant_id=variant_id
        )


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_productvariant'),
        ('inventory', '0002_alter_stockrecord_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockrecord',
            name='product_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_records_legacy', to='catalog.productvariant'),
        ),
        migrations.RunPython(backfill_stock_record_product_variant, migrations.RunPython.noop),
    ]
