# Generated by Django 5.1.6 on 2026-02-09 22:24

import django.db.models.deletion
from django.db import migrations, models


def backfill_main_warehouse_for_inventory(apps, schema_editor):
    warehouse_model = apps.get_model("warehouses", "Warehouse")
    stock_record_model = apps.get_model("inventory", "StockRecord")

    main_warehouse, _ = warehouse_model.objects.get_or_create(
        code="MAIN",
        defaults={
            "name": "Основний склад",
            "kind": "storage",
            "is_default_for_production": True,
            "is_active": True,
        },
    )
    stock_record_model.objects.filter(warehouse_id__isnull=True).update(warehouse_id=main_warehouse.id)


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_productvariant'),
        ('inventory', '0003_stockrecord_product_variant'),
        ('materials', '0007_remove_materialstockrecord_materials_stock_material_unit_null_color_uniq_and_more'),
        ('warehouses', '0002_seed_main_warehouse'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='stockrecord',
            name='inventory_stockrecord_product_color_uniq',
        ),
        migrations.RemoveConstraint(
            model_name='stockrecord',
            name='inventory_stockrecord_product_material_color_uniq',
        ),
        migrations.AddField(
            model_name='stockrecord',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finished_stock_records_legacy', to='warehouses.warehouse'),
        ),
        migrations.RunPython(backfill_main_warehouse_for_inventory, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='stockrecord',
            constraint=models.UniqueConstraint(condition=models.Q(('warehouse__isnull', True)), fields=('product_model', 'color'), name='inventory_stockrecord_product_color_uniq'),
        ),
        migrations.AddConstraint(
            model_name='stockrecord',
            constraint=models.UniqueConstraint(condition=models.Q(('warehouse__isnull', True)), fields=('product_model', 'primary_material_color', 'secondary_material_color'), name='inventory_stockrecord_product_material_color_uniq'),
        ),
        migrations.AddConstraint(
            model_name='stockrecord',
            constraint=models.UniqueConstraint(condition=models.Q(('warehouse__isnull', False)), fields=('warehouse', 'product_model', 'color'), name='inventory_stockrecord_warehouse_product_color_uniq'),
        ),
        migrations.AddConstraint(
            model_name='stockrecord',
            constraint=models.UniqueConstraint(condition=models.Q(('warehouse__isnull', False)), fields=('warehouse', 'product_model', 'primary_material_color', 'secondary_material_color'), name='inventory_stockrecord_warehouse_product_material_color_uniq'),
        ),
    ]
