# Generated by Django 5.1.6 on 2026-02-09 22:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_productvariant'),
        ('inventory', '0004_remove_stockrecord_inventory_stockrecord_product_color_uniq_and_more'),
        ('orders', '0020_order_product_variant'),
        ('warehouses', '0002_seed_main_warehouse'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WIPStockRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wip_stock_records', to='catalog.productvariant')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wip_stock_records', to='warehouses.warehouse')),
            ],
            options={
                'verbose_name': 'WIP залишок',
                'verbose_name_plural': 'WIP залишки',
            },
        ),
        migrations.CreateModel(
            name='WIPStockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_change', models.IntegerField()),
                ('reason', models.CharField(choices=[('cutting_in', 'Порізка в WIP'), ('finishing_out', 'Вибуття з WIP на доробку'), ('scrap_out', 'Списання браку з WIP'), ('adjustment_in', 'Коригування +'), ('adjustment_out', 'Коригування -')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('related_production_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order')),
                ('stock_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.wipstockrecord')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='wipstockrecord',
            constraint=models.UniqueConstraint(fields=('warehouse', 'product_variant'), name='inventory_wipstockrecord_warehouse_variant_uniq'),
        ),
    ]
