# Generated by Django 5.1.6 on 2026-02-09 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_finishedstocktransfer_finishedstocktransferline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='reason',
            field=models.CharField(choices=[('production_in', 'Надходження з виробництва'), ('order_out', 'Відвантаження клієнту'), ('transfer_in', 'Надходження зі складу'), ('transfer_out', 'Переміщення на склад'), ('adjustment_in', 'Коригування +'), ('adjustment_out', 'Коригування -'), ('return_in', 'Повернення')], max_length=20),
        ),
    ]
