# Generated by Django 5.1.6 on 2025-02-09 12:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="etsy",
            field=models.BooleanField(default=False),
        ),
    ]
