# Generated by Django 5.1.6 on 2025-02-20 06:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_notificationsetting"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationsetting",
            name="notify_order_finished_pause",
            field=models.BooleanField(default=True),
        ),
    ]
