# Generated by Django 5.1.6 on 2025-02-20 07:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0003_notificationsetting_notify_order_finished_pause"),
    ]

    operations = [
        migrations.RenameField(
            model_name="notificationsetting",
            old_name="notify_order_finished_pause",
            new_name="notify_order_created_pause",
        ),
    ]
