# Generated by Django 5.1.6 on 2026-02-07 00:00

from django.db import migrations, models


STATUS_CHOICES = [
    ('new', 'Нове'),
    ('embroidery', 'На вишивці'),
    ('almost_finished', 'Майже готове'),
    ('finished', 'Готове'),
    ('on_hold', 'Призупинено'),
]


def backfill_current_status(apps, schema_editor):
    Order = apps.get_model('orders', 'Order')
    OrderStatusHistory = apps.get_model('orders', 'OrderStatusHistory')

    for order in Order.objects.all().only('id', 'finished_at'):
        latest = (
            OrderStatusHistory.objects.filter(order_id=order.id)
            .order_by('-id')
            .first()
        )
        if latest:
            Order.objects.filter(id=order.id).update(current_status=latest.new_status)
            continue

        if order.finished_at is not None:
            Order.objects.filter(id=order.id).update(current_status='finished')


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_rename_notify_order_finished_pause_notificationsetting_notify_order_created_pause'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='current_status',
            field=models.CharField(
                choices=STATUS_CHOICES,
                db_index=True,
                default='new',
                max_length=20,
            ),
        ),
        migrations.RunPython(backfill_current_status, migrations.RunPython.noop),
    ]
