# Generated by Django 5.1.6 on 2026-02-07 19:07

from django.db import migrations, models


def migrate_legacy_almost_finished_to_doing(apps, schema_editor):
    Order = apps.get_model("orders", "Order")
    OrderStatusHistory = apps.get_model("orders", "OrderStatusHistory")
    Order.objects.filter(current_status="almost_finished").update(current_status="doing")
    OrderStatusHistory.objects.filter(new_status="almost_finished").update(new_status="doing")


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_delayednotificationlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='current_status',
            field=models.CharField(choices=[('new', 'Нове'), ('doing', 'Робимо'), ('embroidery', 'Вишиваємо'), ('deciding', 'Рішаємо'), ('on_hold', 'Чогось нема'), ('finished', 'Фініш'), ('almost_finished', 'Майже готове')], db_index=True, default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='new_status',
            field=models.CharField(choices=[('new', 'Нове'), ('doing', 'Робимо'), ('embroidery', 'Вишиваємо'), ('deciding', 'Рішаємо'), ('on_hold', 'Чогось нема'), ('finished', 'Фініш'), ('almost_finished', 'Майже готове')], max_length=20),
        ),
        migrations.RunPython(
            migrate_legacy_almost_finished_to_doing,
            migrations.RunPython.noop,
        ),
    ]
