# Generated by Django 5.1.6 on 2026-02-10 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundlepresetcomponent',
            name='primary_material_color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bundle_preset_primary_components', to='materials.materialcolor'),
        ),
        migrations.AddField(
            model_name='bundlepresetcomponent',
            name='secondary_material_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bundle_preset_secondary_components', to='materials.materialcolor'),
        ),
        migrations.AddField(
            model_name='bundlecolormapping',
            name='bundle_color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_bundle_color', to='catalog.color'),
        ),
        migrations.AddField(
            model_name='bundlecolormapping',
            name='component_color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_component_color', to='catalog.color'),
        ),
        migrations.AddField(
            model_name='product',
            name='primary_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='primary_products', to='materials.material'),
        ),
        migrations.AddField(
            model_name='product',
            name='secondary_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='secondary_products', to='materials.material'),
        ),
        migrations.AddField(
            model_name='bundlepresetcomponent',
            name='component',
            field=models.ForeignKey(limit_choices_to={'is_bundle': False}, on_delete=django.db.models.deletion.CASCADE, related_name='bundle_presets', to='catalog.product'),
        ),
        migrations.AddField(
            model_name='bundlepreset',
            name='bundle',
            field=models.ForeignKey(limit_choices_to={'is_bundle': True}, on_delete=django.db.models.deletion.CASCADE, related_name='presets', to='catalog.product'),
        ),
        migrations.AddField(
            model_name='bundlecomponent',
            name='bundle',
            field=models.ForeignKey(limit_choices_to={'is_bundle': True}, on_delete=django.db.models.deletion.CASCADE, related_name='components', to='catalog.product'),
        ),
        migrations.AddField(
            model_name='bundlecomponent',
            name='component',
            field=models.ForeignKey(limit_choices_to={'is_bundle': False}, on_delete=django.db.models.deletion.CASCADE, related_name='part_of_bundles', to='catalog.product'),
        ),
        migrations.AddField(
            model_name='bundlecolormapping',
            name='bundle',
            field=models.ForeignKey(limit_choices_to={'is_bundle': True}, on_delete=django.db.models.deletion.CASCADE, related_name='color_mappings', to='catalog.product'),
        ),
        migrations.AddField(
            model_name='bundlecolormapping',
            name='component',
            field=models.ForeignKey(limit_choices_to={'is_bundle': False}, on_delete=django.db.models.deletion.CASCADE, related_name='bundle_color_components', to='catalog.product'),
        ),
        migrations.AddField(
            model_name='variant',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='variants', to='catalog.color'),
        ),
        migrations.AddField(
            model_name='variant',
            name='primary_material_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='variants_primary', to='materials.materialcolor'),
        ),
        migrations.AddField(
            model_name='variant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.product'),
        ),
        migrations.AddField(
            model_name='variant',
            name='secondary_material_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='variants_secondary', to='materials.materialcolor'),
        ),
        migrations.AlterUniqueTogether(
            name='bundlepresetcomponent',
            unique_together={('preset', 'component')},
        ),
        migrations.AlterUniqueTogether(
            name='bundlepreset',
            unique_together={('bundle', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='bundlecomponent',
            unique_together={('bundle', 'component')},
        ),
        migrations.AlterUniqueTogether(
            name='bundlecolormapping',
            unique_together={('bundle', 'bundle_color', 'component')},
        ),
        migrations.AddConstraint(
            model_name='variant',
            constraint=models.UniqueConstraint(condition=models.Q(('color__isnull', False), ('primary_material_color__isnull', True), ('secondary_material_color__isnull', True)), fields=('product', 'color'), name='catalog_productvariant_product_color_uniq'),
        ),
        migrations.AddConstraint(
            model_name='variant',
            constraint=models.UniqueConstraint(condition=models.Q(('color__isnull', True), ('primary_material_color__isnull', False), ('secondary_material_color__isnull', True)), fields=('product', 'primary_material_color'), name='catalog_productvariant_primary_only_uniq'),
        ),
        migrations.AddConstraint(
            model_name='variant',
            constraint=models.UniqueConstraint(condition=models.Q(('color__isnull', True), ('primary_material_color__isnull', False), ('secondary_material_color__isnull', False)), fields=('product', 'primary_material_color', 'secondary_material_color'), name='catalog_productvariant_primary_secondary_uniq'),
        ),
        migrations.AddConstraint(
            model_name='variant',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('color__isnull', False), ('primary_material_color__isnull', True)), models.Q(('color__isnull', True), ('primary_material_color__isnull', False)), _connector='OR'), name='catalog_productvariant_color_xor_primary'),
        ),
        migrations.AddConstraint(
            model_name='variant',
            constraint=models.CheckConstraint(condition=models.Q(('secondary_material_color__isnull', True), ('primary_material_color__isnull', False), _connector='OR'), name='catalog_productvariant_secondary_requires_primary'),
        ),
    ]
