# Generated by Django 5.1.6 on 2026-02-09 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_color_created_at_color_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='is_bundle',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='BundleColorMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bundle', models.ForeignKey(limit_choices_to={'is_bundle': True}, on_delete=django.db.models.deletion.CASCADE, related_name='color_mappings', to='catalog.productmodel')),
                ('bundle_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_bundle_color', to='catalog.color')),
                ('component', models.ForeignKey(limit_choices_to={'is_bundle': False}, on_delete=django.db.models.deletion.CASCADE, related_name='bundle_color_components', to='catalog.productmodel')),
                ('component_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_component_color', to='catalog.color')),
            ],
            options={
                'unique_together': {('bundle', 'bundle_color', 'component')},
            },
        ),
        migrations.CreateModel(
            name='BundleComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('bundle', models.ForeignKey(limit_choices_to={'is_bundle': True}, on_delete=django.db.models.deletion.CASCADE, related_name='components', to='catalog.productmodel')),
                ('component', models.ForeignKey(limit_choices_to={'is_bundle': False}, on_delete=django.db.models.deletion.CASCADE, related_name='part_of_bundles', to='catalog.productmodel')),
            ],
            options={
                'ordering': ('-is_primary', 'id'),
                'unique_together': {('bundle', 'component')},
            },
        ),
    ]
