# Generated by Django 5.1.6 on 2026-02-09 20:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_productmodel_is_bundle_bundlecolormapping_and_more'),
        ('materials', '0003_materialcolor'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='primary_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='primary_products', to='materials.material'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='secondary_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='secondary_products', to='materials.material'),
        ),
        migrations.CreateModel(
            name='BundlePreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('archived_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bundle', models.ForeignKey(limit_choices_to={'is_bundle': True}, on_delete=django.db.models.deletion.CASCADE, related_name='presets', to='catalog.productmodel')),
            ],
            options={
                'ordering': ('bundle_id', 'name'),
                'unique_together': {('bundle', 'name')},
            },
        ),
        migrations.CreateModel(
            name='BundlePresetComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.ForeignKey(limit_choices_to={'is_bundle': False}, on_delete=django.db.models.deletion.CASCADE, related_name='bundle_presets', to='catalog.productmodel')),
                ('preset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='catalog.bundlepreset')),
                ('primary_material_color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bundle_preset_primary_components', to='materials.materialcolor')),
                ('secondary_material_color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bundle_preset_secondary_components', to='materials.materialcolor')),
            ],
            options={
                'ordering': ('preset_id', 'component_id'),
                'unique_together': {('preset', 'component')},
            },
        ),
    ]
