# Generated by Django 5.1.6 on 2026-02-09 21:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_productmodel_primary_material_and_more'),
        ('materials', '0006_alter_materialstockrecord_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('legacy_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_variants', to='catalog.color')),
                ('primary_material_color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_variants_primary', to='materials.materialcolor')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.productmodel')),
                ('secondary_material_color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_variants_secondary', to='materials.materialcolor')),
            ],
            options={
                'ordering': ('product_id', 'id'),
                'constraints': [models.UniqueConstraint(condition=models.Q(('color__isnull', False), ('primary_material_color__isnull', True), ('secondary_material_color__isnull', True)), fields=('product', 'color'), name='catalog_productvariant_product_color_uniq'), models.UniqueConstraint(condition=models.Q(('color__isnull', True), ('primary_material_color__isnull', False), ('secondary_material_color__isnull', True)), fields=('product', 'primary_material_color'), name='catalog_productvariant_primary_only_uniq'), models.UniqueConstraint(condition=models.Q(('color__isnull', True), ('primary_material_color__isnull', False), ('secondary_material_color__isnull', False)), fields=('product', 'primary_material_color', 'secondary_material_color'), name='catalog_productvariant_primary_secondary_uniq'), models.CheckConstraint(condition=models.Q(models.Q(('color__isnull', False), ('primary_material_color__isnull', True)), models.Q(('color__isnull', True), ('primary_material_color__isnull', False)), _connector='OR'), name='catalog_productvariant_color_xor_primary'), models.CheckConstraint(condition=models.Q(('secondary_material_color__isnull', True), ('primary_material_color__isnull', False), _connector='OR'), name='catalog_productvariant_secondary_requires_primary')],
            },
        ),
    ]
