# Generated by Django 5.1.6 on 2026-02-13 17:31

from django.db import migrations, models
from django.db.models import Count


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_productmaterial'),
        ('materials', '0001_initial'),
    ]

    @staticmethod
    def _dedupe_primary_secondary_roles(apps, schema_editor) -> None:
        ProductMaterial = apps.get_model("catalog", "ProductMaterial")
        Product = apps.get_model("catalog", "Product")

        dupes = (
            ProductMaterial.objects.filter(role__in=["primary", "secondary"])
            .values("product_id", "role")
            .annotate(c=Count("id"))
            .filter(c__gt=1)
        )
        for item in dupes:
            product_id = item["product_id"]
            role = item["role"]
            rows = list(
                ProductMaterial.objects.filter(product_id=product_id, role=role).order_by("id")
            )
            product = Product.objects.filter(pk=product_id).first()

            keep = None
            if product and role == "primary" and getattr(product, "primary_material_id", None):
                keep = next(
                    (pm for pm in rows if pm.material_id == product.primary_material_id),
                    None,
                )
            if product and role == "secondary" and getattr(product, "secondary_material_id", None):
                keep = next(
                    (pm for pm in rows if pm.material_id == product.secondary_material_id),
                    None,
                )
            if keep is None and rows:
                keep = rows[0]

            for pm in rows:
                if keep and pm.id == keep.id:
                    continue
                pm.role = "other"
                pm.save(update_fields=["role"])

    operations = [
        migrations.RunPython(_dedupe_primary_secondary_roles, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='productmaterial',
            constraint=models.UniqueConstraint(condition=models.Q(('role', 'primary')), fields=('product',), name='catalog_productmaterial_primary_uniq_per_product'),
        ),
        migrations.AddConstraint(
            model_name='productmaterial',
            constraint=models.UniqueConstraint(condition=models.Q(('role', 'secondary')), fields=('product',), name='catalog_productmaterial_secondary_uniq_per_product'),
        ),
    ]
