# Generated by Django 5.1.6 on 2026-02-13 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_productmaterial_catalog_productmaterial_primary_uniq_per_product_and_more'),
        ('materials', '0002_delete_bom'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmaterial',
            name='quantity_per_unit',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='productmaterial',
            name='unit',
            field=models.CharField(blank=True, choices=[('pcs', 'шт'), ('m', 'м'), ('m2', 'м²'), ('g', 'г'), ('ml', 'мл')], max_length=8, null=True),
        ),
        migrations.AddConstraint(
            model_name='productmaterial',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('quantity_per_unit__isnull', True), ('unit__isnull', True)), models.Q(('quantity_per_unit__isnull', False), ('unit__isnull', False)), _connector='OR'), name='catalog_productmaterial_norm_quantity_unit_nullability'),
        ),
    ]
