# Generated by Django 5.1.6 on 2026-02-13 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_productmaterial_quantity_per_unit_and_more'),
    ]

    @staticmethod
    def _set_kind_from_is_bundle(apps, schema_editor) -> None:
        Product = apps.get_model("catalog", "Product")
        Product.objects.filter(is_bundle=True).update(kind="bundle")

    @staticmethod
    def _set_is_bundle_from_kind(apps, schema_editor) -> None:
        Product = apps.get_model("catalog", "Product")
        Product.objects.filter(kind="bundle").update(is_bundle=True)

    operations = [
        migrations.AddField(
            model_name='product',
            name='kind',
            field=models.CharField(choices=[('standard', 'Звичайний'), ('component', 'Компонент'), ('bundle', 'Бандл')], db_index=True, default='standard', max_length=16),
        ),
        migrations.RunPython(
            code=_set_kind_from_is_bundle,
            reverse_code=_set_is_bundle_from_kind,
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_bundle',
        ),
        migrations.AlterField(
            model_name='bundlecolormapping',
            name='bundle',
            field=models.ForeignKey(limit_choices_to={'kind': 'bundle'}, on_delete=django.db.models.deletion.CASCADE, related_name='color_mappings', to='catalog.product'),
        ),
        migrations.AlterField(
            model_name='bundlecolormapping',
            name='component',
            field=models.ForeignKey(limit_choices_to=models.Q(('kind', 'standard'), ('kind', 'component'), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, related_name='bundle_color_components', to='catalog.product'),
        ),
        migrations.AlterField(
            model_name='bundlecomponent',
            name='bundle',
            field=models.ForeignKey(limit_choices_to={'kind': 'bundle'}, on_delete=django.db.models.deletion.CASCADE, related_name='components', to='catalog.product'),
        ),
        migrations.AlterField(
            model_name='bundlecomponent',
            name='component',
            field=models.ForeignKey(limit_choices_to=models.Q(('kind', 'standard'), ('kind', 'component'), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, related_name='part_of_bundles', to='catalog.product'),
        ),
        migrations.AlterField(
            model_name='bundlepreset',
            name='bundle',
            field=models.ForeignKey(limit_choices_to={'kind': 'bundle'}, on_delete=django.db.models.deletion.CASCADE, related_name='presets', to='catalog.product'),
        ),
        migrations.AlterField(
            model_name='bundlepresetcomponent',
            name='component',
            field=models.ForeignKey(limit_choices_to=models.Q(('kind', 'standard'), ('kind', 'component'), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, related_name='bundle_presets', to='catalog.product'),
        ),
    ]
