# Generated by Django 5.1.6 on 2026-02-13 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_remove_product_is_bundle_product_kind_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='allows_embroidery',
            field=models.BooleanField(default=True),
        ),
    ]
