# Generated by Django 5.1.6 on 2026-02-14 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0012_color_code_optional"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="kind",
            field=models.CharField(
                choices=[("standard", "Виріб"), ("bundle", "Комплект"), ("component", "Компонент")],
                db_index=True,
                default="standard",
                max_length=16,
            ),
        ),
    ]

